---
title: 'Input y vocabulario infantil en las actividades cotidianas (póster)'
author: ''
date: '2021-12-11'
slug: poster-input-y-vocabulario-infantil-en-las-actividades-cotidianas
categories: []
tags: 
 - educacion
 - español
 - poster
subtitle: 'Trabajo presentado en el VI Encuentro de Investigadores en Desarrollo, Aprendizaje y Educación'
summary: 'En este trabajo analicé la relación entre el input y el vocabulario productivo infantil durante las actividades cotidianas en el marco del hogar.'
authors: []
lastmod: '2021-12-11T11:55:24-03:00'
featured: yes
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
projects: [investigacion]
---

La investigación presentada en [este póster](https://figshare.com/articles/poster/Input_y_vocabulario_infantil_en_las_actividades_cotidianas_un_estudio_naturalista_con_diversos_grupos_sociales/16965814?backTo=/collections/2_Escuela_y_hogar/5703160) forma parte de mi proyecto de investigación. Si bien pueden leer los detalles técnicos en el póster, en este post voy a comentar brevemente cuál es la lógica detrás de la investigación.

Para quienes no vengan del lado de la lingüística o de la adquisición del lenguaje, un poco de contexto. Mi trabajo y el de mi equipo toman como marco teórico los modelos basados en enfoques socioculturales que plantean una interrelación entre el desarrollo cognitivo y el desarrollo lingüístico: esto significa que la maduración cognitiva del bebé desencandena el aprendizaje del lenguaje, pero es este mismo aprendizaje (y uso) del lenguaje el que tracciona esa maduración cognitiva. No son procesos independientes entre sí, ni tampoco uno es causa absoluta del otro, sino que funcionan de forma interdependiente. Todo esto ocurre siempre en el contexto de la interacción social tanto en los núcleos familiares como en los comunitarios. Esto significa, entonces, que las experiencias tempranas que el niño tenga son formativas, porque es esa interacción con el otro y esas experiencias novedosas las que llevarán al niño a desarrollar nuevas habilidades.

Es en este contexto que lo que ocurre alrededor de él se vuelve crucial. En lingüística a esto se lo denomina *input*, una palabra heredada de los primeros enfoques psicolingüísticos basados en las primeras teorías chomskyanas, en las cuales el lenguaje que el bebé escuchara sería el insumo que necesita para reconocer las características de la lengua que debe adquirir. Si bien el término *input* se sigue utilizando para referirse al lenguaje al cual el niño está expuesto, el enfoque que utilizo en este trabajo difiere un poco de cómo se concebía ese lenguaje en estas teorías. Las primeras propuestas entendían ese *input* como una forma de habla incompleta y muchas veces incorrecta, lo cual les llevaba a entender que debía haber un componente lingüístico innato que le permitiera al infante desarrollar un lenguaje completo a partir de esa información imprecisa (no me maten, compañeros lingüistas, por esta generalización). Los enfoques basados en el uso vienen de alguna forma a revalorizar el rol que este *input* tiene en la adquisición del lenguaje; entre ellas, cabe destacar las posturas de [Michael Tomasello](https://books.google.com.ar/books/about/Constructing_a_Language.html?id=7M_lSEfzTQoC&redir_esc=y) y de [Katherine Nelson](https://www.cambridge.org/core/books/language-in-cognitive-development/07485B37EADA322456204A31001691C1).

Entonces, ¿qué pasa con ese contexto? ¿Cómo es ese lenguaje que escuchan los niños durante sus primeros años de vida? ¿Cómo impacta o cómo se relaciona con el lenguaje que utilizan los niños? Esa es un poco la pregunta que nos hacemos en mi equipo. Entre las líneas de investigación, estudiamos el desarrollo del vocabulario, las funciones pragmáticas, la adquisición de la transitividad, el uso del lenguaje en discursos narrativos, argumentativos y explicativos. Algunas investigaciones se realizan a partir de pruebas cuasi-experimentales y otras, como la mía, con corpus.

Y esto nos lleva a este póster, que no es el primero que he presentado, pero sí es el primero del cual escribo tanto en este blog. Mi proyecto de investigación está orientado a estudiar el uso del vocabulario en niños pequeños, y actualmente estoy trabajando con un corpus de habla espontánea tomado en el marco del hogar de niños y niñas de cuatro años. Dado que la población argentina se caracteriza por una fragmentación social muy marcada, se eligieron familias que pertenecieran a dos polos opuestos en el *continuum* de las circunstancias socioeconómicas, caracterizadas por la ubicación del hogar y por el nivel educativo. Se grabaron los intercambios durante doce horas, en distintos momentos del día; por lo tanto, este acercamiento nos permite preguntarnos acerca del uso del lenguaje en las distintas actividades cotidianas. Sabemos que las personas, tanto adultos como niños, no utilizan el lenguaje de la misma forma en los distintos momentos del día: comparen situaciones como, por ejemplo, la limpieza del hogar y otras como una lectura de cuentos. Hay actividades donde los niños son el foco de la atención, como situaciones de baño o de juegos, y hay otras donde ellos están escuchando lo que ocurre con otras personas, cuando por ejemplo los adultos conversan entre sí o realizan actividades domésticas.

Esto nos llevó a clasificar las actividades en tres grandes grupos: en primer lugar, aquellas actividades cuyo foco es la vida hogareña y la crianza, como las situaciones de comida y de higiene, otras actividades donde el foco es el niño, como los juegos, los momentos de dibujo, lectura y alfabetización, y finalmente actividades centradas en adultos, como actividades domésticas de limpieza o conversaciones entre ellos. Identificamos los segmentos donde se llevaban a cabo estas actividades y analizamos el lenguaje utilizado en estos grupos.

Pensamos tres medidas: la cantidad de turnos de habla, la diversidad léxica (es decir, la probabilidad de que en ese fragmento surjan palabras nuevas) y los distintos tipos de palabras diferenciadas en sustantivos, adjetivos y verbos. Realizamos tres tipos de pruebas estadísticas:

-   Una **prueba de hipótesis** para identificar diferencias entre los grupos en cada una de estas medidas, al interior de cada tipo de actividad.

-   Un **análisis de la varianza** para identificar diferencias entre las distintas actividades en cada una de estas medidas, al interior de cada grupo.

-   Una **regresión beta** para identificar si el tipo de actividad y la pertenencia al grupo podría explicar el uso de los distintos tipos de sustantivos, adjetivos y verbos tanto por el *input* como por los niños.

Los resultados, a grandes rasgos, indicaron que no hubo diferencias entre grupos ni en la cantidad de turnos de habla que las familias produjeron en cada tipo de actividad ni en la diversidad léxica. Es decir, al tener en cuenta los distintos tipos de actividades, las familias de los dos grupos (tanto el niño como las demás personas que componen su *input*) tuvieron un comportamiento similar. Al comparar los distintos tipos de actividades, aquellas centras en los niños fueron las que promovieron una mayor cantidad de turnos de habla y una mayor diversidad léxica. Esto se vuelve relevante en cuanto a que, tal vez, estas actividades puedan ser espacios ricos para el desarrollo del lenguaje: en términos de transferencia, esto podría traducirse en comunicar a las familias y a las comunidades la importancia de generar este tipo de actividades en el marco del hogar (y de los espacios educativos, por supuesto).

Encontramos diferencias también al mirar las proporciones de clases de palabras: las actividades centradas en los niños aumentaron significativamente la proporción de sustantivos y de adjetivos por parte de los niños, mientras que bajaron la proporción de verbos; este patrón se repitió en el *input* con excepción de los adjetivos, que no se vieron particularmente promovidos por ninguna de estas actividades. Estos resultados son interesantes porque, si bien todas las clases de palabras tienen el mismo nivel de importancia en la adquisición del vocabulario, es posible que el acceso a ellas sea distinto. Un vocabulario más rico y más diverso, en cualquier dirección, significa una mayor posibilidad de expresión de las experiencias que las personas viven; si pensamos además que el aprendizaje de la lectoescritura se apoya en gran parte del conocimiento lingüístico previo, se vuelve importante pensar en cuáles pueden ser los aspectos de esta alfabetización inicial que más impactan con las experiencias previas de los niños.

Este trabajo se realizó con doce transcripciones: el objetivo es codificar la totalidad de las transcripciones que forman parte del corpus. Por otro lado, creemos que puede ser interesante mirar al interior de los grupos de actividades que conformamos: ¿hay diferencias entre las situaciones de lectura y las situaciones de juego?

Para citar este póster:

Quiroga, M., Rosemberg, C., Alam, F., & Lewinsky, V.. (2021). *Input y vocabulario infantil en las actividades cotidianas: un estudio naturalista con diversos grupos sociales* (Version 1). figshare. <https://doi.org/10.6084/m9.figshare.16965814.v1>
