---
title: 'Input and child vocabulary during daily activities (poster)'
author: ''
date: '2021-12-11'
slug: poster-input-y-vocabulario-infantil-en-las-actividades-cotidianas
categories: []
tags: 
 - education
 - english
 - poster
subtitle: ''
summary: 'In this paper I analyzed the relationship between input and child productive vocabulary during daily activities in the home setting.'
authors: []
lastmod: '2021-12-11T11:55:24-03:00'
featured: yes
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
projects: [investigation]
---

The research presented in[this poster](https://figshare.com/articles/poster/Input_y_vocabulario_infantil_en_las_actividades_cotidianas_un_estudio_naturalista_con_diversos_grupos_sociales/16965814?backTo=/collections/2_Escuela_y_hogar/5703160) (in spanish) is part of my research project. While you can read the technical details on the poster, in this post I'm going to briefly comment on the logic behind the research.

For those not coming from the linguistics or language acquisition side, a bit of context. My work and that of my team take as a theoretical framework the models based on sociocultural approaches that propose an interrelation between cognitive development and linguistic development: this means that the cognitive maturation of the baby triggers language learning, but it is this very learning (and use) of language that drives this cognitive maturation. They are not independent processes, nor is one the absolute cause of the other, but they work interdependently. All this always occurs in the context of social interaction in both family and community nuclei. This means, then, that the early experiences that the child has are formative, because it is that interaction with the other and those novel experiences that will lead the child to develop new skills.

In this framework,what happens around them becomes crucial. In linguistics this is called *input*, a word inherited from the first psycholinguistic approaches based on the first Chomskyan theories, in which the language that the baby heard would be the input that they need to recognize the characteristics of the language that they must acquire. Although the term *input* is still used to refer to the language to which the child is exposed, the approach I use in this paper differs somewhat from how that language was conceived in these theories. The first proposals understood that *input* as an incomplete and often incorrect form of speech, which led them to understand that there should be an innate linguistic component that would allow the infant to develop a complete language from that imprecise information (please don't kill me, fellow linguists, because of this generalization). Approaches based on use somehow come to reassess the role that this *input* has in language acquisition; Among them, it is worth highlighting the positions of [Michael Tomasello](https://books.google.com.ar/books/about/Constructing_a_Language.html?id=7M_lSEfzTQoC&redir_esc=y) and [Katherine Nelson](https://www.cambridge.org/core/books/language-in-cognitive-development/07485B37EADA322456204A31001691C1).

So what about the linguistic environment? How is that language that children hear during their first years of life? How does it impact or how is it related to the language used by children? That's kind of the question we ask ourselves in my team. Among the lines of research, we study the development of vocabulary, pragmatic functions, the acquisition of transitivity, the use of language in narrative, argumentative and explanatory discourses. Some investigations are carried out from quasi-experimental tests and others, like mine, with corpus.

And this brings us to this poster, which is not the first one that I have presented, but it is the first one that I write so much about in this blog. My research project is aimed at studying the use of vocabulary in young children, and I am currently working with a corpus of spontaneous speech taken in the home setting of four-year-old boys and girls. Given that the Argentine population is characterized by a very marked social fragmentation, families were chosen that belonged to two opposite poles in the *continuum* of socioeconomic circumstances, characterized by the location of the home and by the educational level. The exchanges were recorded for twelve hours, at different times of the day; therefore, this approach allows us to ask ourselves about the use of language in different daily activities. We know that people, both adults and children, do not use language in the same way at different times of the day: just think about situations such as cleaning the house and others such as reading stories. There are activities where children are the focus of attention, such as bathing or playing situations, and there are others where they are listening to what is happening with other people, when, for example, adults talk to each other or do household activities.

This led us to classify the activities into three large groups: first, those activities whose focus is home life and parenting, such as food and hygiene situations, other activities where the focus is the child, such as games, the moments of drawing, reading and literacy, and finally activities focused on adults, such as housekeeping activities or conversations between them. We identified the segments where these activities were carried out and analyzed the language used in these groups.

We think of three measures: the number of turns of speech, lexical diversity (that is, the probability that new words will appear in that fragment) and the different types of words differentiated into nouns, adjectives and verbs. We perform three types of statistical tests:

- A **hypothesis test** to identify differences between the groups in each of these measures, within each type of activity.

- An **analysis of variance** to identify differences between the different activities in each of these measures, within each group.

- A **beta regression** to identify whether the type of activity and group membership could explain the use of the different types of nouns, adjectives and verbs by both the *input* and the children.

Broadly speaking, the results indicated that there were no differences between groups in the number of speaking turns that families produced in each type of activity or in lexical diversity. That is, when taking into account the different types of activities, the families of the two groups (both the child and the other people who make up his *input*) had a similar behaviour. When comparing the different types of activities, those focused on children were the ones that promoted a greater number of speaking turns and a greater lexical diversity. This becomes relevant in that, perhaps, these activities can be rich spaces for language development: in terms of interventions, this could translate into communicating to families and communities the importance of generating this type of activity in the framework of the home (and educational spaces, of course).

We found differences also when looking at the proportions of word classes: child-focused activities significantly increased children's proportion of nouns and adjectives, while lowering the proportion of verbs; this pattern appeared also in the *input* with the exception of adjectives, which were not particularly promoted by any of these activities. These results are interesting because, although all word classes have the same level of importance in vocabulary acquisition, it is possible that access to them is different. A richer and more diverse vocabulary, in any direction, means a greater possibility of expression of the experiences that people live; if we also think that the literacy processes are based on a large part of prior linguistic knowledge, it becomes important to think about what may be the aspects of this initial literacy that have the greatest impact on the children's previous experiences.

This work was carried out with twelve transcripts: the objective is to codify all the transcripts that are part of the corpus. On the other hand, we believe that it may be interesting to look inside the groups of activities that we make up: are there differences between reading situations and game situations?

To quote this poster:

Quiroga, M., Rosemberg, C., Alam, F., & Lewinsky, V.. (2021). *Input y vocabulario infantil en las actividades cotidianas: un estudio naturalista con diversos grupos sociales* (Version 1). figshare. <https://doi.org/10.6084/m9.figshare.16965814.v1>
