---
title: Narrative production in the context of social isolation due to SARS-CoV-2. An exploratory study of technology-mediated interactions
author: ''
date: '2021-09-25'
slug: aacc2021-narratives
categories: []
tags: 
 - investigacion
 - narrativas
 - poster
 - español
subtitle: ''
summary: 'Poster presented in the Reunión AACC 2021'
authors: []
lastmod: '2021-09-19T16:01:22-03:00'
featured: yes
image:
  caption: ''
  focal_point: 'Center'
  preview_only: no
projects: []
---

## Narrative production in the context of social isolation due to SARS-CoV-2. An exploratory study of technology-mediated interactions

Quiroga, Macarena Sol (CIIPME-CONICET/UNaHur); Lewinsky, Viviana (IICE/UBA); González Lynn, Eliana (UBA); Ramírez, María Laura (CIIPME-CONICET); Audisio, Cynthia Pamela (CIIPME-CONICET); Franco Accinelli, Ailín Paula (CIIPME-CONICET); Ibañez, María Ileana (CIIPME-CONICET); Giordano, Carla (CIIPME-CONICET); Rosemberg, Celia Renata (CIIPME-CONICET/IICE/UBA).

Link to the presentation [HERE](https://www.youtube.com/watch?v=dJ__eMTDmbQ).

### Introduction

Narratives are a way to reconstruct and communicate our own experience and to understand other's experiences. The development of the child narrative discourse begins at two-year-old during interactions with adults, both at home and school. Nowadays, the isolation due to the restrictions to contain the SARS-CoV-2 pandemic reconfigured everyday interactions and brought about changes in children's early linguistic experiences. One of the most extended modifications was the use of video-calls with the purpose of maintaining social contact and sustaining the educational continuity. The incorporation of this new communication channel to everyday life enables the exploration of new linguistic usage. For example, it has been noted that, during video-calls with family members, adults collaborate with children in the narrative production. However, no studies that analysed narrative production technology-mediated in the context of social isolation were found.

### Goals

In this study we intend to analyse the discursive and situational properties of the narrative sequences technology-mediated during the social isolation. A non-probabilistic convenience sample (Hernández Sampieri, 2010) was collected, and it was integrated by narratives produced in 101 spontaneous situations involving technology (video-calls, cellphone play, etc.) in which 2 to 6-year-old children participated in their homes (more tan 170 minutes of video footage, corpus: Rosemberg et al, 2020, in progress). The footage were made and sent by family members, who gave their informed consent to the scientific use of the videos.

### Methods

The narratives were encoded using the Constant Comparative Method (Strauss & Corbin, 1990) according to its type (personal experience, future event and fictional stories) and to the way it was sustained (self-regulation, heteroregulation and shared regulation), children's age and the temporal relation between the emission and reception of the narrative 
(synchronous or asynchronous). We used the ELAN software (Max Planck Institute for Psycholinguistics, 2018) for segmentation, transcription and codification. We used descriptive measures to explore the distribution in the corpus.

### Results

Preliminary analysis allowed us to identify 35 narrative sequences. Most of them were personal experiences (53%), though we also found future events narratives (22%) and fictional stories (25%). In addition, a 45% of the narratives had heteroregulation, i.e. were controlled by other participants, while a 26% of the narratives had a share regulation, and a 31% of them were regulated by the child. Most of the self-regulated narratives took place in asynchronous interactions (73%); instead, during the synchronous interactions, the narratives were most frequently co-constructed with others, both with a heteregulation (54%) and with a shared regulation (36%).

### Discussion

In this first approximation to the study of technology-mediated interactions during the social isolation, we observed that these interactions give rise to a various types of narratives that had different kinds of regulations. The mediator role of the technology presents new possibilities for children to use and develop their linguistic resources.


Palabras clave: narrativas; interacciones mediadas con tecnología, experiencias tempranas Keywords: narratives; technology-mediated interactions, early experiences
