---
title: Student Conference, or how to promote the valorization of different ways of
  talking
author: ''
date: '2021-09-19'
slug: student-conference-or-how-to-promote-the-valorization-of-different-ways-of-talking
categories: []
tags: 
  - education
  - english
subtitle: ''
summary: 'Yesterday, Saturday, September 18, the 1st Conference for English Students was held at the National University of Hurlingham. In this text I present some of my motivations to organize it.'
authors: []
lastmod: '2021-09-19T16:01:22-03:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: [teaching]
---
Yesterday the 1st Conference of Students of English-Teacher training was held at the National University of Hurlingham, an event that I promoted together with two of my fellow teachers. I am interested in highlighting, in this text, the reasons that led me to propose it.

The first time I heard about this type of meeting was during my undergraduate studies in Literature at the University of Buenos Aires. The meeting was called ENEL: National Meeting of Liteature and Linguistics Students and, as its name indicates, it was the space destined for the presentation of works carried out by students, whether in literature, linguistics or philology. The logic of these events is to create a safe, horizontal space where the work done by students can be presented. In many cases, the presentations arose from partial or monographs made in the courses; in others, they were approximations to topics of interest. Participants had to be undergraduate students. The entire meeting was organized by the local headquarters team: at the end of the event, a plenary session was held where all the people who wanted to participate participated, a closing was carried out and the next venue was chosen. This meeting brought together students from universities from all over the country: that is how I traveled to Rosario and Mendoza as an assistant, because I did not feel prepared to present.

The second experience, already a little further along in my career, was with the Jornadas de Jovenes Lingüistas [Young Linguists Workshop]. In this case, although the focus is also on creating spaces to take the first steps in the discipline, the cut is no longer just undergraduate students, but also non-doctoral graduates. This event is organized by students and recent graduates, linked to the Institute of Linguistics of the Faculty of Philosophy and Literature of the University of Buenos Aires, where the Conference is held.

It was at this event when I made my first presentation: at the II Conference in 2013. Together with a colleague, I presented a work that emerged from our own experience as high school teachers: we had observed a recurrent problem in syntactic analysis and we decided to carry out a small investigation to explain what could be due. Today I think about that work and I find thousands of flaws in it; however, all I received from the exhibition audience was encouragement and suggestions to keep thinking about the topic. I don't remember who was in the audience, but surely there were people who noticed those shortcomings that I notice today. The difference is precisely in the spirit of the Conference: a space to start, to try, to practice. Unfortunately, the academic field is not always characterized by being patient, understanding and supportive: sometimes presenting papers at academic events can feel like going through a slaughterhouse.

I write that line and immediately ask myself: why would we want to invite our students to participate in events that can feel like slaughterhouses? And the truth is that not all academic conferences feel this way, but when it does, it is a situation for which you better be prepared.

Exhibiting at an academic event, like any complex sociocultural experience, implies many layers of novelty for those who do it for the first time. The first layer is the textual dimension, that is, choosing one's own work, reviewing it, presenting the abstract, receiving feedback, adapting it to orality, creating the audiovisual support. The second layer is the performative dimension: presenting oneself in front of others, presenting the work orally, looking at their expressions and reactions, listening to the questions, improvising the answers. And the third, the most difficult in my opinion, is the authorial dimension: the presentation of academic works outside the space of a university subject, for example, implies becoming authors of our own texts. And this can be very difficult, because becoming authors also implies building an authority figure within the discipline; In other words, when we present a work we show ourselves to the other as producers of valid knowledge and we place ourselves within the disciplinary scene as one more interlocutor. This requires a lot, I mean, *a lot* of self-confidence, and it is not so easy to achieve, because the educational dynamics in which the students participate are necessarily asymmetric, where the student is the non-expert who learns from the expert, be it the teacher, or the author of the text. Presenting an academic paper is a situation that breaks this dynamic, since the exhibitor presents himself as a peer in front of the other exhibitors and as an expert in front of the audience.

There are some aspects of these dimensions that are built throughout life: the third, sure; the second, maybe. But the first dimension, the writing process, is something that can be practised, and it is a dimension that is there, at hand, in any higher education experience. Students are constantly writing academic texts, even if they don't realize it; they are constantly creating new knowledge, because no matter how much it is already known content, they are giving it their own imprint. That is what these spaces come to say: the subjective imprints on the academic contents are the added value that justifies the presence of any of these works in an academic event.

However, accepting oneself as an author -third dimension- can take years: if we sit down and wait to feel ready to present, then we will never do it. It is in this sense that, if we can build spaces where they do not have to worry about this dimension, where they can be sure that the event is tailor-made for them and their moment in the race, then we will be giving them a unique opportunity to practice the first two dimensions. In this way, we make sure that their first experiences as exhibitors are enjoyable and that, in the event that they have to go through a slaughterhouse situation at another time in life, they have the tools to cope with it. Furthermore, above all things, participating in these spaces assures them that the academic world does not have to feel this way. Spaces for debate and exchange of knowledge can be created without a competitive gaze, but instead of mutual growth.

Beyond this, I believe that spaces such as these Conferences are not only important for practicing oral presentations. I think they are also an excellent opportunity for people to ask themselves what area, what aspect of the career or discipline interests them the most. Sometimes works are presented that already had a form close to what is required (for example, a monograph), but sometimes students take the opportunity to return to some interesting idea or some question that had been spinning in their heads. And I believe that this operation is also enriching for professional development, because although they will all have the same title, not all of them are interested in the same topics. Finding one's own specialty or orientation within one's career and disciplinary field is a central aspect of professional development: why not start earlier?

Finally, the last great reason for creating events like these is that it opens the communication channel. Most of the communicative situations that occur in university spaces have a limited scope: although all students listen simultaneously to what the teachers say, they do not have the same access to the productions of their classmates. And that situation facilitates the feeling of loneliness and insecurity. Instead, listening and reading what other classmates have to say helps to feel accompanied and to feel part of the same educational process. Not all interactions that revolve around an academic text have to be limited to evaluation.

And how difficult it is to feel part of an educational community when what we have in front of us are black squares on a screen! I think that another unexpected benefit of these Conferences was that it reminded us of the voices of those who are on the other side, in this moment of pandemic that has so undermined our social ties. When I think that there are students who have already been studying for a year and a half but have not yet visited the University campus, my heart squeezes a little.

I hope then that this event has served not only for everyone to feel that they have something to say, that their academic productions are valid and that we want to listen to them, but also that the ties that are created in the university space are still valid. A little more difficult, a little further away, a little more affected by complex circumstances, but they are still there. And yesterday we saw them.