---
title: Avances con el libro Text Mining with R
author: ''
date: '2022-04-15'
slug: avances-con-el-libro-text-mining-with-r
categories: []
tags:
  - data science
  - español
subtitle: ''
summary: ''
authors: []
lastmod: '2022-04-15T11:48:13-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: [ciencia-de-datos]
---

Hoy terminé con el capítulo 4 del libro [Text Mining with R](https://www.tidytextmining.com/preface.html) de Julia Silge y David Robinson. Dado que mi objetivo es que sirva como práctica, no solamente incluyo el código sino también los comentarios y la propuesta teórica. En algunos casos, además, incluyo información sobre funciones o términos que no conocía antes.

Cada capítulo es un archivo rmarkdown en mi repo de github:

-   [Capítulo 1: formato tidy-text](https://github.com/msquiroga89/TextMiningWithR/blob/main/Cap%201_Tidytext%20format.Rmd)

-   [Capítulo 2: análisis de sentimiento](https://github.com/msquiroga89/TextMiningWithR/blob/main/Cap%202_Sentiment%20analysis%20with%20tidy%20data.Rmd)

-   [Capítulo 3: análisis de frecuencia de palabras y de documentos con td-idf](https://github.com/msquiroga89/TextMiningWithR/blob/main/Cap%203_Analyzing%20word%20and%20document%20frequency_tf-idf.Rmd)

-   [Capítulo 4: relaciones entre palabras con n-grams y correlaciones](https://github.com/msquiroga89/TextMiningWithR/blob/main/Cap%204_Relations%20between%20words_n%20grams%20and%20correlations.Rmd)

Espero que estos materiales le sirvan a quien quiera aprender sobre análisis de texto, pero no se sienta tan cómodx con el inglés. Si necesitan una mano, no tengo problema en ayudar.
